// src/views/NewBoard.vue
<template>
  <v-container>
    <v-row>
      <v-col md="4" offset-md="4">
        <h2 class="text-center">Criar um quadro novo</h2>
        <v-form v-model="valid">
          <v-text-field
            v-model="boardName"
            label="Nome do quadro"
            :rules="boardNameRules"
            required />
          <v-text-field
            v-model="userName"
            label="Seu nome"
            :rules="userNameRules"
            required />
          <v-btn
            @click="goBoard"
            class="mt-2"
            color="primary"
            block
            large
            :disabled="disableCreateButton">
            <span class="mr-1">Criar</span>
            <v-icon>mdi-folder-plus</v-icon>
          </v-btn>
        </v-form>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import { createBoard } from '../services/boardsDatabase';
import { get as getStorage } from '../services/storage';

export default {
  name: 'NewBoard',
  data() {
    return {
      boardName: '',
      boardNameRules: [
        (v) => (!!v && v.length > 5) || 'O nome do quadro precisa ter mais do que 5 caracteres.',
      ],
      userName: getStorage('userName') || '',
      userNameRules: [
        (v) => (!!v && v.length > 0) || 'É preciso informar um nome para prosseguir.',
      ],
      valid: true,
    };
  },
  computed: {
    disableCreateButton() {
      return !this.valid;
    },
  },
  methods: {
    async goBoard() {
      try {
        // TODO: move this logic to New Board view
        const boardId = await createBoard(this.boardName, this.userName);

        this.$router.push({ name: 'Board', params: { boardId } });
      } catch (err) {
        console.log('🚀 ~ newBoard ~ err', err);
      }
    },
  },
};
</script>

// src/pages/new-board.tsx
import Button from '@components/Button';
import TextField from '@components/TextField';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { createBoard } from '../services/boardsDatabase';

const NewBoard: NextPage = () => {
  const router = useRouter();

  const [boardName, setBoardName] = useState(null);
  const [userName, setUserName] = useState(null);

  const handleGoBoard = async () => {
    try {
      // TODO: move this logic to New Board view
      const boardId = await createBoard(boardName, userName);
      console.log('🚀 ~ handleGoBoard ~ boardId', boardId);
      router.push(`/board/${boardId}`);
    } catch (err) {
      console.log('🚀 ~ newBoard ~ err', err);
    }
  };

  const handleChangeBoardName = el => {
    setBoardName(el.target.value);
  };

  const handleChangeUserName = el => {
    setUserName(el.target.value);
  };

  return (
    <section className="block mx-auto md:max-w-[600px]">
      <div className="flex flex-col gap-4 mx-5 my-6">
        <h2 className="text-2xl text-center mb-3">Criar um quadro novo</h2>
        <TextField type="text" label="Nome do quadro" onChange={handleChangeBoardName} />
        <TextField type="text" label="Seu nome" onChange={handleChangeUserName} />
      </div>
      <div className="flex justify-center mx-5 mt-5">
        <Button variant="primary" onClick={handleGoBoard} fullWidth>
          Criar
        </Button>
      </div>
    </section>
  );
};

export default NewBoard;
